from config.settings import *

ENV = "CAP"   # DEV / PROD

if ENV == "CAP":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_CAP
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_CAP
    BASE_URL_MOODLE = BASE_URL_MOODLE_CAP
    MOODLE_TOKEN=MOODLE_TOKEN_DEV

elif ENV == "PROD":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_PROD
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_PROD
    BASE_URL_MOODLE = BASE_URL_MOODLE_PROD
    MOODLE_TOKEN=MOODLE_TOKEN_PROD