from config.settings import *

ENV = "PROD"   # DEV / CAP / PROD

if ENV == "CAP":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_CAP
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_CAP
    BASE_URL_MOODLE = BASE_URL_MOODLE_CAP
    MOODLE_TOKEN = MOODLE_TOKEN_DEV

    # API SIFODS: URL base para gestión de usuarios (crear/consultar)
    SIFODS_API_BASE_URL = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_CAP
    SIFODS_API_TOKEN    = ""
    SIFODS_API_TIMEOUT  = 30
    SIFODS_API_BATCH_SIZE = 500

    # RENIEC y Perfil Docente
    URL_RENIEC           = BASE_URL_RENIEC_CAP
    URL_PERFIL_DOCENTE   = BASE_URL_SIFODS_PERFIL_DOCENTE_CAP

elif ENV == "PROD":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_PROD
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_PROD
    BASE_URL_MOODLE = BASE_URL_MOODLE_PROD
    MOODLE_TOKEN = MOODLE_TOKEN_PROD

    # API SIFODS: URL base para gestión de usuarios (crear/consultar)
    SIFODS_API_BASE_URL = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_PROD
    SIFODS_API_TOKEN    = ""
    SIFODS_API_TIMEOUT  = 30
    SIFODS_API_BATCH_SIZE = 500

    # RENIEC y Perfil Docente
    URL_RENIEC           = BASE_URL_RENIEC_PROD
    URL_PERFIL_DOCENTE   = BASE_URL_SIFODS_PERFIL_DOCENTE_PROD