from config.settings import *

ENV = "CAP"   # DEV / PROD

if ENV == "CAP":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_CAP
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_CAP
    BASE_URL_MOODLE = BASE_URL_MOODLE_CAP
    MOODLE_TOKEN = MOODLE_TOKEN_DEV

    # API SIFODS: URL base para gestión de usuarios (crear/consultar)
    SIFODS_API_BASE_URL = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_CAP
    SIFODS_API_TOKEN    = ""   # Sin token requerido en CAP
    SIFODS_API_TIMEOUT  = 30
    SIFODS_API_BATCH_SIZE = 500

elif ENV == "PROD":
    BASE_URL_ACCIONES_FORMATIVAS = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_PROD
    BASE_URL_ADMINISTRADOR_PLATAFORMA = BASE_URL_SIFODS_ADMINISTRADOR_PLATAFORMA_PROD
    BASE_URL_MOODLE = BASE_URL_MOODLE_PROD
    MOODLE_TOKEN = MOODLE_TOKEN_PROD

    # API SIFODS: URL base para gestión de usuarios (crear/consultar)
    SIFODS_API_BASE_URL = BASE_URL_SIFODS_ACCIONES_FORMATIVAS_PROD
    SIFODS_API_TOKEN    = ""   # Configurar token PROD si aplica
    SIFODS_API_TIMEOUT  = 30
    SIFODS_API_BATCH_SIZE = 500